-- SoundsManifest.lua — GENERATED by tools/build-sound-manifest.sh.
-- DO NOT HAND-EDIT: re-running the script overwrites this file.
--
-- Lists the audio sitting in Sounds/. The files themselves are NOT in this
-- repo (Sounds/ is gitignored) — this is only the index that lets the Hub
-- know what exists, since WoW cannot enumerate files. An EMPTY table is the
-- correct shipped state: on anyone else's machine these register nothing.
--
-- Everything here is registered into LibSharedMedia at login, which is what
-- puts it in Gloom's Auras' sound picker and every other LSM-aware addon.

local GloomsHub = _G.GloomsHub
if not GloomsHub then return end

GloomsHub.SOUND_MANIFEST = {
}
