#!/usr/bin/env bash
#
# build-sound-manifest.sh — regenerate SoundsManifest.lua from the Sounds/ folder.
#
# WoW exposes no filesystem API: an addon cannot list a folder or test whether a
# file exists. So dropping .ogg files into Sounds/ does nothing on its own —
# something outside the game has to tell the Hub what is there. That is this
# script. Drop sounds into Sounds/, run this, /reload.
#
# The display name is derived from the filename: the extension is dropped,
# underscores and hyphens become spaces, and CamelCase is split.
#
#   Sounds/AirHorn.ogg          -> "Air Horn"
#   Sounds/TempleBellHuge.ogg   -> "Temple Bell Huge"
#   Sounds/cat_meow_2.ogg       -> "cat meow 2"
#
# Sounds/ is gitignored — your audio never enters the repo, which also keeps
# third-party sound files out of a public release. SoundsManifest.lua IS
# tracked, and holds nothing but name->filename pairs. Committing a POPULATED
# manifest is a mistake: it ships an index to files nobody else has.

set -euo pipefail
cd "$(dirname "$0")/.."

DIR="Sounds"
OUT="SoundsManifest.lua"

mkdir -p "$DIR"

entries=""
count=0
skipped=0

# Sorted, NUL-safe, and tolerant of an empty folder.
while IFS= read -r -d '' f; do
  base="$(basename "$f")"
  case "$base" in
    .*) continue ;;                     # dotfiles (.DS_Store, probes)
  esac
  ext="$(printf '%s' "${base##*.}" | tr '[:upper:]' '[:lower:]')"
  if [ "$ext" != "ogg" ] && [ "$ext" != "mp3" ]; then
    printf '  SKIP (WoW plays only .ogg/.mp3): %s\n' "$base" >&2
    skipped=$((skipped + 1))
    continue
  fi

  stem="${base%.*}"
  # _ and - become spaces; split camelCase and letter/digit boundaries; squeeze.
  name="$(printf '%s' "$stem" \
    | sed -e 's/[_-]\{1,\}/ /g' \
          -e 's/\([a-z0-9]\)\([A-Z]\)/\1 \2/g' \
          -e 's/\([A-Za-z]\)\([0-9]\)/\1 \2/g' \
          -e 's/  */ /g' \
          -e 's/^ //' -e 's/ $//')"
  [ -n "$name" ] || name="$stem"

  # Lua string escape: backslashes and quotes. Filenames should not contain
  # either, but generating code from filenames without escaping is how you get a
  # syntax error that looks like a game bug.
  escName="$(printf '%s' "$name" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  escFile="$(printf '%s' "$base" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  entries="${entries}  { name = \"${escName}\", file = \"${escFile}\" },
"
  count=$((count + 1))
done < <(find "$DIR" -maxdepth 1 -type f -print0 2>/dev/null | sort -z)

{
  echo "-- SoundsManifest.lua — GENERATED by tools/build-sound-manifest.sh."
  echo "-- DO NOT HAND-EDIT: re-running the script overwrites this file."
  echo "--"
  echo "-- Lists the audio sitting in Sounds/. The files themselves are NOT in this"
  echo "-- repo (Sounds/ is gitignored) — this is only the index that lets the Hub"
  echo "-- know what exists, since WoW cannot enumerate files. An EMPTY table is the"
  echo "-- correct shipped state: on anyone else's machine these register nothing."
  echo "--"
  echo "-- Everything here is registered into LibSharedMedia at login, which is what"
  echo "-- puts it in Gloom's Auras' sound picker and every other LSM-aware addon."
  echo ""
  echo "local GloomsHub = _G.GloomsHub"
  echo "if not GloomsHub then return end"
  echo ""
  echo "GloomsHub.SOUND_MANIFEST = {"
  printf '%s' "$entries"
  echo "}"
} > "$OUT"

printf 'wrote %s — %d sound(s), %d skipped\n' "$OUT" "$count" "$skipped"
